GET         http://localhost:5000/api/ingredients
Content-Type: application/json

  {
    "name": "Refractario o molde",
    "units": ["unidad"],
    "defaultUnit": "unidad",
    "category": "Utensilios"
  }
 