
GET  http://localhost:5000/api/recipes
Content-Type: application/json

{
  "title": "Queso de leche ecuatoriano",
  "imageUrl": "https://cdn0.recetasgratis.net/es/posts/0/5/8/queso_de_leche_ecuatoriano_41850_orig.jpg",
  "description": "Postre tradicional ecuatoriano, similar al flan, elaborado con leche, huevos, azúcar, canela y vainilla. Suave y cremoso, perfecto para ocasiones especiales.",
  "timeRequired": 60,
  "servings": 8,
  "difficulty": "Principiante",
  "type": "Postres",
  "ingredients": [
    { "ingredient": "6859d3bc6f7e60404dc8ff0f", "quantity": 10, "unit": "unidad" },
    { "ingredient": "6859d3a56f7e60404dc8ff0b", "quantity": 450, "unit": "gramo" },
    { "ingredient": "6859d3796f7e60404dc8ff05", "quantity": 1000, "unit": "mililitro" },
    { "ingredient": "6859d3b16f7e60404dc8ff0d", "quantity": 2, "unit": "rama" },
    { "ingredient": "6859d3c96f7e60404dc8ff11", "quantity": 1, "unit": "cucharadita" },
    { "ingredient": "6859d6006f7e60404dc8ff75", "quantity": 2, "unit": "cucharada" }
  ],
  "steps": [
    "Pon a hervir la leche con las ramas de canela y el azúcar, reservando 1/4 de taza de azúcar aparte.",
    "Cuando el azúcar se haya disuelto y la leche espese ligeramente, retira del fuego, cuela la mezcla y deja enfriar.",
    "Agrega los huevos, la esencia de vainilla y la maicena. Bate todo durante 10 minutos hasta obtener una crema suave.",
    "Prepara un caramelo con el azúcar reservada y una cucharada de agua; vierte el caramelo en el fondo de un molde.",
    "Vierte la mezcla de leche sobre el caramelo y hornea a 180°C durante 30 minutos.",
    "Deja enfriar antes de desmoldar y servir."
  ]
}
