### Crear receta
POST http://localhost:5000/api/recipes
Content-Type: application/json

{
  "title": "Baleadas hondureñas",
  "imageUrl": "https://www.recetasgratis.net/files/receta-de-baleadas-hondurenas-74138-1200.jpg",
  "description": "Receta típica hondureña con frijoles, queso y aguacate.",
  "timeRequired": 15,
  "servings": 2,
  "rating": 4.5,
  "tags": ["ecuatoriana"],
  "ingredients": [
    "683645cfa2c53d3f02ee911a",
    "683646ffa2c53d3f02ee9195",
    "68364133a2c53d3f02ee9023"
  ],
  "steps": [
    "Calienta las tortillas de harina en una sartén.",
    "Unta los frijoles refritos sobre cada tortilla.",
    "Agrega queso rallado y rodajas de aguacate.",
    "Dobla cada tortilla por la mitad y sirve caliente."
  ]
}